version: '3.9'

services:
  postgres:
    image: postgres:16.2
    ports:
      - "${DB_PORT:-5432}:${DB_INTERNAL_PORT:-5432}"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
volumes:
  data: {}
